package com.smartcity.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

@Service
public class EmailService {

    private static final Logger log = LoggerFactory.getLogger(EmailService.class);

    private final JavaMailSender mailSender;

    @Value("${spring.mail.username:notifications@smartcity.gov.in}")
    private String fromEmail;

    public EmailService(JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }

    @Async
    public void sendAlertNotification(String toEmail, String subject, String alertTitle, String alertDescription) {
        try {
            log.info("Preparing SMTP email notification to '{}' | Subject: '{}'", toEmail, subject);

            SimpleMailMessage message = new SimpleMailMessage();
            message.setFrom(fromEmail);
            message.setTo(toEmail);
            message.setSubject("🚨 [Smart City AI Alert] " + subject);
            
            String content = String.format(
                "SMART CITY AI PLATFORM — NOTIFICATION ALERT\n" +
                "====================================================\n\n" +
                "ALERT TITLE: %s\n\n" +
                "DETAILS:\n%s\n\n" +
                "----------------------------------------------------\n" +
                "This is an automated AI alert generated by the Smart City AI System.\n" +
                "Please log in to the Smart City Dashboard to take appropriate action.\n" +
                "http://localhost:8080/",
                alertTitle,
                alertDescription
            );
            
            message.setText(content);

            mailSender.send(message);
            log.info("Successfully sent SMTP email alert to '{}'", toEmail);

        } catch (Exception e) {
            log.warn("Could not dispatch SMTP email alert to '{}' (Reason: {}). AI Alert logged locally.", toEmail, e.getMessage());
        }
    }
}
