spring.application.name=smart-city-backend
server.port=${PORT:8082}

# MySQL Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/smart_city_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Mathan@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Python ML Microservice
ml.service.base-url=${ML_SERVICE_BASE_URL:http://localhost:8000}

# JWT Authorization
jwt.secret=${JWT_SECRET:SuperSecretKey123!SuperSecretKey123!SuperSecretKey123!}
jwt.expiration-ms=86400000

# SMTP Mail Dispatch
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:vbsattanathan@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:lhao uqmc didd qwea}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000

# File upload configuration
file.upload-dir=uploads/complaints
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.mail.properties.mail.smtp.writetimeout=5000

